### PR TITLE
refactor: cleanup generate-embeddings.ts

### PR DESCRIPTION
**Pull request by iuioiua**
This change:
- Moves to using functionality already offered in the Deno Standard Library and in-built Node compatibility layer.
- Uses npm specifiers for Node packages instead of esm.sh
- Centralises imports into `import_map.json`

"The major advantage of nom specifiers is that you don't have to rely on 3rd party service to transpile them and Deno's static analysis is more precise than esm.sh due to being run locally. That allows you to load Node-API files and data files from packages. This is not really possible with esm.sh" - Bartek at Deno

### CODE REVIEW

**Comment by iuioiua** [comment]
`extractMetaExport()` only ever returns `undefined`. Is this just because of the given test mdx file? Does this case also apply to the rest of the actual dataset? If so, it might be worth removing the function.

**Comment by iuioiua** [comment]
PTAL, @thorwebdev.

**Review by thorwebdev — APPROVED** [review]
This is great, thank you! 

Do we need to add a note around `npm specifiers` and that they currently can only be used for the scripts that run outside of deno deploy?

**Comment by iuioiua** [comment]
Note added.

**Pull request merged**
